# Generated by Django 6.0.6 on 2026-06-17 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_remove_grade_add_pph21_ter'),
        ('organization', '0002_employee_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeGrade',
        ),
    ]
