# Generated by Django 6.0.6 on 2026-06-17 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alignment_hris_tahap1'),
        ('organization', '0003_remove_grade_add_pph21_ter'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=100)),
                ('rank', models.PositiveSmallIntegerField(default=0, help_text='Urutan hierarki (1 = terendah).')),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['rank', 'code'],
                'unique_together': {('tenant', 'code')},
            },
        ),
    ]
