from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from apps.web import views
from apps.web.admin_crud import views as manage_views
from apps.web.auth_views import HRISLoginView, HRISLogoutView

app_name = "web"

urlpatterns = [
    path("login/", HRISLoginView.as_view(), name="login"),
    path("logout/", HRISLogoutView.as_view(), name="logout"),
    path("", views.dashboard, name="dashboard"),
    path("punch/", views.punch_action, name="punch"),
    path("manage/", manage_views.manage_hub, name="manage_hub"),
    path("manage/<slug:slug>/", manage_views.resource_list, name="manage_list"),
    path("manage/<slug:slug>/new/", manage_views.resource_create, name="manage_create"),
    path("manage/<slug:slug>/<int:pk>/edit/", manage_views.resource_edit, name="manage_edit"),
    path("manage/<slug:slug>/<int:pk>/delete/", manage_views.resource_delete, name="manage_delete"),
    path("master/", manage_views.master_hub, name="master_hub"),
    path("master/<slug:slug>/", manage_views.master_resource_list, name="master_list"),
    path("master/<slug:slug>/new/", manage_views.master_resource_create, name="master_create"),
    path("master/<slug:slug>/<int:pk>/edit/", manage_views.master_resource_edit, name="master_edit"),
    path("master/<slug:slug>/<int:pk>/delete/", manage_views.master_resource_delete, name="master_delete"),
    path("employees/", views.employee_list, name="employee_list"),
    path("employees/new/", views.employee_create, name="employee_create"),
    path("employees/<int:pk>/edit/", views.employee_edit, name="employee_edit"),
    path("employees/<int:pk>/deactivate/", views.employee_deactivate, name="employee_deactivate"),
    path("employees/import/", views.employee_import, name="employee_import"),
    path("employees/import/template/", views.employee_import_template, name="employee_import_template"),
    path("profile/", views.employee_profile, name="employee_profile"),
    path("shifts/", views.shift_assignment_list, name="shift_assignment_list"),
    path("shifts/assign/", views.shift_assign, name="shift_assign"),
    path("shifts/<int:pk>/edit/", views.shift_edit, name="shift_edit"),
    path("shifts/<int:pk>/delete/", views.shift_delete, name="shift_delete"),
    path("attendance/", views.attendance_list, name="attendance_list"),
    path("attendance/import/", views.attendance_import, name="attendance_import"),
    path("attendance/import/template/", views.attendance_import_template, name="attendance_import_template"),
    path("attendance/export/", views.attendance_export, name="attendance_export"),
    path("leave/", views.leave_list, name="leave_list"),
    path("leave/new/", views.leave_create, name="leave_create"),
    path("leave/<int:pk>/approve/", views.leave_approve, name="leave_approve"),
    path("leave/<int:pk>/reject/", views.leave_reject, name="leave_reject"),
    path("leave/<int:pk>/cancel/", views.leave_cancel, name="leave_cancel"),
    path("overtime/", views.overtime_list, name="overtime_list"),
    path("overtime/new/", views.overtime_create, name="overtime_create"),
    path("overtime/<int:pk>/approve/", views.overtime_approve, name="overtime_approve"),
    path("overtime/<int:pk>/reject/", views.overtime_reject, name="overtime_reject"),
    path("overtime/<int:pk>/cancel/", views.overtime_cancel, name="overtime_cancel"),
    path("payroll/", views.payroll_list, name="payroll_list"),
    path("payroll/new/", views.payroll_create, name="payroll_create"),
    path("payroll/<int:pk>/", views.payroll_detail, name="payroll_detail"),
    path("payroll/<int:pk>/edit/", views.payroll_edit, name="payroll_edit"),
    path("payroll/<int:pk>/cancel/", views.payroll_cancel, name="payroll_cancel"),
    path("payroll/<int:pk>/calculate/", views.payroll_calculate, name="payroll_calculate"),
    path("payroll/<int:pk>/finalize/", views.payroll_finalize, name="payroll_finalize"),
    path("payroll/<int:pk>/bank-export/", views.payroll_bank_export, name="payroll_bank_export"),
    path("payroll/<int:pk>/bpjs-export/", views.payroll_bpjs_export, name="payroll_bpjs_export"),
    path("payroll/<int:pk>/pph21-export/", views.payroll_pph21_export, name="payroll_pph21_export"),
    path("payroll/<int:pk>/validate/", views.payroll_validate, name="payroll_validate"),
    path("payslips/", views.payslip_list, name="payslip_list"),
    path("payslips/<int:pk>/download/", views.payslip_download, name="payslip_download"),
    path("notifications/", views.notification_list, name="notification_list"),
    path("notifications/<int:pk>/read/", views.notification_mark_read, name="notification_mark_read"),
    path("notifications/read-all/", views.notification_mark_all_read, name="notification_mark_all_read"),
    path("audit/", views.audit_log_list, name="audit_log_list"),
]
