# Generated by Django 6.0.6 on 2026-06-12 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_announcement'),
        ('employees', '0003_alter_employee_allowance_meal_and_more'),
        ('shifts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DaySwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requestor_work_date', models.DateField(db_index=True)),
                ('counterpart_work_date', models.DateField(db_index=True)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Menunggu Rekan'), ('pending_approval', 'Menunggu Atasan'), ('approved', 'Disetujui'), ('rejected', 'Ditolak'), ('cancelled', 'Dibatalkan')], default='pending', max_length=20)),
                ('counterpart_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('counterpart_rejected_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_day_swap_requests', to=settings.AUTH_USER_MODEL)),
                ('counterpart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_swap_requests_received', to='employees.employee')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_swap_requests_sent', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status', '-created_at'], name='shifts_days_tenant__456c06_idx')],
            },
        ),
    ]
