# Generated by Django 6.0.6 on 2026-06-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0005_shift_tenant_scoped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='plant',
        ),
        migrations.AlterField(
            model_name='shift',
            name='cross_day',
            field=models.BooleanField(default=False, help_text='Night shift: clock in on work date, clock out the next calendar day.'),
        ),
    ]
