# Generated by Django 6.0.6 on 2026-06-11 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification'),
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='default_shift',
            field=models.ForeignKey(blank=True, help_text='Shift otomatis untuk karyawan baru di plant ini.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_plants', to='shifts.shift'),
        ),
    ]
