# Generated by Django 6.0.6 on 2026-06-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_onboarding_overtime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at'], 'permissions': [('purge_auditlog', 'Can purge archived audit logs (management command only)')]},
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_tenant_model_idx',
            old_name='core_auditl_tenant__3c5be2_idx',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='integrity_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 tamper-evidence hash (append-only records).', max_length=64),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tenant', '-created_at'], name='audit_tenant_created_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tenant', 'object_id', 'model_name'], name='audit_tenant_object_idx'),
        ),
    ]
