# Generated by Django 6.0.6 on 2026-06-12 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_audit_integrity_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, help_text='Ringkasan singkat untuk banner dan daftar.', max_length=500)),
                ('body', models.TextField(help_text='Konten lengkap pengumuman.')),
                ('category', models.CharField(choices=[('general', 'Umum'), ('policy', 'Kebijakan'), ('hr', 'SDM & HR'), ('payroll', 'Payroll & Benefit'), ('safety', 'K3 & Keselamatan'), ('event', 'Acara & Kegiatan'), ('it', 'IT & Sistem'), ('urgent', 'Penting / Darurat')], default='general', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Rendah'), ('normal', 'Normal'), ('high', 'Tinggi'), ('critical', 'Kritis')], default='normal', max_length=20)),
                ('target_roles', models.JSONField(blank=True, default=list, help_text='Daftar role yang ditargetkan. Kosong = semua role.')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('publish_start', models.DateTimeField()),
                ('publish_end', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_pinned', models.BooleanField(default=False, help_text='Tampil di atas pengumuman lain.')),
                ('require_acknowledgment', models.BooleanField(default=False, help_text='Pengguna harus menutup/mengakui sebelum banner hilang.')),
                ('attachment', models.FileField(blank=True, upload_to='announcements/%Y/%m/')),
                ('external_link', models.URLField(blank=True)),
                ('action_label', models.CharField(blank=True, help_text='Label tombol aksi eksternal, mis. Baca panduan lengkap.', max_length=80)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_created', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(blank=True, help_text='Kosongkan untuk semua plant dalam tenant.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='core.plant')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-is_pinned', '-publish_start'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissals', to='core.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_dismissals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['tenant', 'is_active', '-publish_start'], name='core_announ_tenant__7e661c_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['tenant', 'plant', 'is_active'], name='core_announ_tenant__34e14a_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementdismissal',
            index=models.Index(fields=['user', 'announcement'], name='core_announ_user_id_191435_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='announcementdismissal',
            unique_together={('announcement', 'user')},
        ),
    ]
