# Generated by Django 6.0.6 on 2026-06-17 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='branch_type',
            field=models.CharField(blank=True, choices=[('bps_harian', 'PT BPS Harian'), ('bps_staff', 'PT BPS Staff'), ('spv_up', 'SPV ke atas'), ('other', 'Lainnya')], default='other', max_length=32),
        ),
        migrations.AddField(
            model_name='plant',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='geo_fence_radius_m',
            field=models.PositiveIntegerField(blank=True, help_text='Radius geo-fence absen (meter). Default 150 jika koordinat diisi.', null=True),
        ),
        migrations.CreateModel(
            name='PunchLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('radius_m', models.PositiveIntegerField(default=150)),
                ('is_active', models.BooleanField(default=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punch_locations', to='core.plant')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('leave', 'Cuti'), ('overtime', 'Lembur'), ('attendance_correction', 'Koreksi absensi')], max_length=32)),
                ('step_order', models.PositiveSmallIntegerField(default=1)),
                ('approver_kind', models.CharField(choices=[('direct_manager', 'Atasan langsung'), ('hr_plant', 'HR plant'), ('hr_tenant', 'HR tenant')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['request_type', 'step_order'],
                'unique_together': {('tenant', 'request_type', 'step_order')},
            },
        ),
        migrations.CreateModel(
            name='HolidayCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('holiday_date', models.DateField()),
                ('holiday_type', models.CharField(choices=[('national', 'Libur nasional'), ('company', 'Libur perusahaan'), ('plant', 'Libur plant')], default='national', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='core.plant')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-holiday_date'],
                'unique_together': {('tenant', 'holiday_date', 'name')},
            },
        ),
    ]
