# Generated by Django 6.0.6 on 2026-06-18 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_plant_entity_type'),
        ('shifts', '0006_remove_shift_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='branch_type',
            field=models.CharField(blank=True, choices=[('bps_harian', 'BPS Harian'), ('bps_staff', 'BPS Staff'), ('spv_up', 'SPV Up'), ('other', 'Other')], default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='plant',
            name='default_shift',
            field=models.ForeignKey(blank=True, help_text='Shift otomatis untuk karyawan baru di cabang ini.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_plants', to='shifts.shift'),
        ),
    ]
