# Generated by Django 6.0.6 on 2026-06-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='approval_step',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
