# Generated by Django 6.0.6 on 2026-06-10 07:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=8)),
                ('label', models.CharField(max_length=100)),
                ('payroll_impact', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('deduct', 'Deduction'), ('none', 'None')], default='none', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_date', models.DateField(db_index=True)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('kiosk', 'Kiosk'), ('import', 'Import'), ('manual', 'Manual')], default='web', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-work_date', 'employee'],
            },
        ),
        migrations.CreateModel(
            name='DailyTimesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_date', models.DateField(db_index=True)),
                ('shift_code', models.CharField(blank=True, max_length=32)),
                ('shift_label', models.CharField(blank=True, max_length=100)),
                ('scheduled_check_in', models.TimeField(blank=True, null=True)),
                ('scheduled_check_out', models.TimeField(blank=True, null=True)),
                ('time_off_code', models.CharField(blank=True, max_length=32)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('late_in_minutes', models.PositiveIntegerField(default=0)),
                ('early_out_minutes', models.PositiveIntegerField(default=0)),
                ('schedule_working_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('actual_working_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('paid_working_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('ot_before_minutes', models.PositiveIntegerField(default=0)),
                ('ot_after_minutes', models.PositiveIntegerField(default=0)),
                ('hourly_time_off_taken', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('hourly_time_off_breakdown', models.JSONField(blank=True, default=list)),
                ('calculation_status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-work_date', 'employee'],
            },
        ),
    ]
