# Generated by Django 6.0.6 on 2026-06-11 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_onboarding_overtime'),
        ('core', '0003_onboarding_overtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=100)),
                ('day_category', models.CharField(choices=[('workday', 'Hari Kerja'), ('holiday_6h', 'Hari Libur (6 jam pertama)'), ('holiday_8h', 'Hari Libur (≤8 jam)')], max_length=20)),
                ('hour_from', models.PositiveSmallIntegerField(default=1)),
                ('hour_to', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('multiplier', models.DecimalField(decimal_places=2, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['day_category', 'hour_from', 'code'],
                'unique_together': {('tenant', 'code')},
            },
        ),
    ]
