# Generated by Django 6.0.6 on 2026-06-11 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_overtime_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimerequest',
            name='overtime_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overtime_requests', to='attendance.overtimetype'),
        ),
    ]
