# Generated by Django 6.0.6 on 2026-06-17 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alignment_hris_tahap1'),
        ('employees', '0008_p0_production_hardening'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('employee', 'work_date')},
        ),
    ]
