# Generated by Django 6.0.6 on 2026-06-17 07:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_p0_production_hardening'),
        ('core', '0006_alignment_hris_tahap1'),
        ('employees', '0008_p0_production_hardening'),
        ('shifts', '0003_delete_dayswaprequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['employee', 'check_out'], name='attendance_emp_open_co_idx'),
        ),
    ]
