# Generated by Django 6.0.6 on 2026-06-19 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_punch_spike_indexes'),
        ('core', '0008_talenta_employee_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='core.plant'),
        ),
        migrations.AlterField(
            model_name='dailytimesheet',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_timesheets', to='core.plant'),
        ),
    ]
