# Generated by Django 6.0.6 on 2026-06-12 03:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_audit_integrity_indexes'),
        ('employees', '0003_alter_employee_allowance_meal_and_more'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thrrun',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='THRPayslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('months_worked', models.PositiveSmallIntegerField(default=12)),
                ('base_reference', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('thr_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thr_payslips', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('thr_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.thrrun')),
            ],
            options={
                'ordering': ['employee__full_name'],
                'unique_together': {('thr_run', 'employee')},
            },
        ),
    ]
