# Generated by Django 6.0.6 on 2026-06-17 02:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_announcement'),
        ('payroll', '0002_thrrun_finalized_at_thrpayslip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pph21TerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Kategori TER PPh 21',
                'verbose_name_plural': 'Kategori TER PPh 21',
                'ordering': ['code'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Pph21TerBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bracket_no', models.PositiveSmallIntegerField()),
                ('income_from', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('income_to', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=8)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='payroll.pph21tercategory')),
            ],
            options={
                'verbose_name': 'Lapisan TER PPh 21',
                'verbose_name_plural': 'Lapisan TER PPh 21',
                'ordering': ['category', 'bracket_no'],
                'unique_together': {('tenant', 'category', 'bracket_no')},
            },
        ),
        migrations.CreateModel(
            name='Pph21TerPtkpMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ptkp_code', models.CharField(max_length=16)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ptkp_mappings', to='payroll.pph21tercategory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'verbose_name': 'PTKP → TER',
                'verbose_name_plural': 'PTKP → TER',
                'ordering': ['ptkp_code'],
                'unique_together': {('tenant', 'ptkp_code')},
            },
        ),
    ]
