# Generated by Django 6.0.6 on 2026-06-19 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_talenta_employee_fields'),
        ('payroll', '0004_shift_allowance_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollrun',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs', to='core.plant'),
        ),
        migrations.AlterField(
            model_name='thrrun',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thr_runs', to='core.plant'),
        ),
    ]
