# Generated by Django 6.0.6 on 2026-06-10 07:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.CharField(db_index=True, max_length=64)),
                ('full_name', models.CharField(max_length=200)),
                ('nik', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('resign_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('probation', 'Probation'), ('permanent', 'Permanent'), ('contract', 'Contract'), ('intern', 'Intern'), ('inactive', 'Inactive'), ('resigned', 'Resigned')], default='probation', max_length=20)),
                ('salary_scheme', models.CharField(choices=[('monthly', 'Monthly'), ('daily', 'Daily')], default='monthly', max_length=20)),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('allowance_transport', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('allowance_meal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('allowance_position', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account_number', models.CharField(blank=True, max_length=64)),
                ('bank_account_name', models.CharField(blank=True, max_length=200)),
                ('npwp', models.CharField(blank=True, max_length=32)),
                ('tax_status', models.CharField(blank=True, max_length=16)),
                ('bpjs_kesehatan_number', models.CharField(blank=True, max_length=32)),
                ('bpjs_ketenagakerjaan_number', models.CharField(blank=True, max_length=32)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organization.department')),
                ('job_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organization.jobposition')),
                ('legal_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organization.legalentity')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='employees.employee')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='core.plant')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('ktp', 'KTP'), ('npwp', 'NPWP'), ('contract', 'Contract'), ('diploma', 'Diploma'), ('bpjs', 'BPJS Card'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='employee_documents/%Y/%m/')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['tenant', 'plant', 'status'], name='employees_e_tenant__adbbb8_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['tenant', 'nik'], name='employees_e_tenant__df4cb8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('tenant', 'employee_id')},
        ),
    ]
