# Generated by Django 6.0.6 on 2026-06-12 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('organization', '0002_employee_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organization.employeegrade', verbose_name='Grade karyawan'),
        ),
    ]
