# Generated by Django 6.0.6 on 2026-06-12 03:12

import apps.core.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='allowance_meal',
            field=apps.core.fields.EncryptedDecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='employee',
            name='allowance_position',
            field=apps.core.fields.EncryptedDecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='employee',
            name='allowance_transport',
            field=apps.core.fields.EncryptedDecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_account_name',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_account_number',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='employee',
            name='base_salary',
            field=apps.core.fields.EncryptedDecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bpjs_kesehatan_number',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bpjs_ketenagakerjaan_number',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nik',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='employee',
            name='npwp',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=512),
        ),
    ]
