# Generated by Django 6.0.6 on 2026-06-17 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_default_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_grade',
        ),
        migrations.AddField(
            model_name='employee',
            name='pph21_deduct',
            field=models.BooleanField(blank=True, help_text='Null = otomatis potong jika PTKP diisi. False = tidak dipotong.', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tax_status',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
