# Generated by Django 6.0.6 on 2026-06-17 06:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_remove_grade_add_pph21_ter'),
        ('organization', '0004_alignment_hris_tahap1'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_place',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Laki-laki'), ('female', 'Perempuan')], max_length=16),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organization.joblevel'),
        ),
        migrations.AddField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Belum menikah'), ('married', 'Menikah'), ('divorced', 'Cerai'), ('widowed', 'Janda/Duda')], max_length=16),
        ),
        migrations.AddField(
            model_name='employee',
            name='mother_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='document_type',
            field=models.CharField(choices=[('ktp', 'KTP'), ('kk', 'KK'), ('npwp', 'NPWP'), ('contract', 'Contract'), ('diploma', 'Diploma'), ('bpjs', 'BPJS Card'), ('other', 'Other')], max_length=20),
        ),
    ]
