# Generated by Django 6.0.6 on 2026-06-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_backfill_mandatory_na'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Laki-laki'), ('female', 'Perempuan'), ('na', 'N/A')], max_length=16),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Belum menikah'), ('married', 'Menikah'), ('divorced', 'Cerai'), ('widowed', 'Janda/Duda'), ('na', 'N/A')], max_length=16),
        ),
    ]
