# Generated by Django 6.0.6 on 2026-06-18 09:24

import apps.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_talenta_employee_fields'),
        ('employees', '0009_employee_status_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='barcode',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='employee',
            name='citizen_id_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_tax_status',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='employee',
            name='length_of_service',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='employee',
            name='npwp_16_digit',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_number',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_landline',
            field=models.CharField(blank=True, help_text='Phone (Talenta)', max_length=32),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_picture_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='employee',
            name='sign_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='talenta_age',
            field=models.CharField(blank=True, help_text='Age dari export Talenta', max_length=16),
        ),
        migrations.AddField(
            model_name='employee',
            name='tax_config',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='employee',
            name='tax_ref_doc_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='tax_ref_doc_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='employee',
            name='tax_ref_doc_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='employee',
            name='tin',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, help_text='Residential Address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_end_date',
            field=models.DateField(blank=True, help_text='End Date', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, help_text='Mobile Phone (Talenta)', max_length=32),
        ),
        migrations.CreateModel(
            name='TalentaMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('religion', 'Religion'), ('blood_type', 'Blood Type'), ('nationality', 'Nationality Code'), ('currency', 'Currency'), ('payment_schedule', 'Payment Schedule'), ('approval_line', 'Approval Line'), ('grade', 'Grade'), ('employee_class', 'Class'), ('cost_center', 'Cost Center'), ('cost_center_category', 'Cost Center Category'), ('sbu', 'SBU'), ('employee_tax_status', 'Employee Tax Status'), ('tax_config', 'Tax Config')], max_length=32)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='approval_line',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'approval_line'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_approval_line', to='employees.talentamaster'),
        ),
        migrations.AddField(
            model_name='employee',
            name='blood_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'blood_type'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_blood_type', to='employees.talentamaster'),
        ),
        migrations.AddField(
            model_name='employee',
            name='cost_center',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'cost_center'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_cost_center', to='employees.talentamaster'),
        ),
        migrations.AddField(
            model_name='employee',
            name='cost_center_category',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'cost_center_category'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_cost_center_category', to='employees.talentamaster'),
        ),
        migrations.AddField(
            model_name='employee',
            name='currency',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'currency'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_currency', to='employees.talentamaster'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_tax_status_master',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'employee_tax_status'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_tax_status', to='employees.talentamaster'),
        ),
        migrations.AddField(
            model_name='employee',
            name='grade',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'grade'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_grade', to='employees.talentamaster'),
        ),
        migrations.AddField(
            model_name='employee',
            name='nationality',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'nationality'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_nationality', to='employees.talentamaster'),
        ),
        migrations.AddField(
            model_name='employee',
            name='payment_schedule',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'payment_schedule'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_payment_schedule', to='employees.talentamaster'),
        ),
        migrations.AddField(
            model_name='employee',
            name='religion',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'religion'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_religion', to='employees.talentamaster'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sbu',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'sbu'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_sbu', to='employees.talentamaster'),
        ),
        migrations.AddField(
            model_name='employee',
            name='talenta_class',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'employee_class'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_class', to='employees.talentamaster'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tax_config_master',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'tax_config'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_tax_config', to='employees.talentamaster'),
        ),
        migrations.AddIndex(
            model_name='talentamaster',
            index=models.Index(fields=['tenant', 'category', 'is_active'], name='employees_t_tenant__97919b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='talentamaster',
            unique_together={('tenant', 'category', 'name')},
        ),
    ]
