# Generated by Django 6.0.6 on 2026-06-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_talenta_employee_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_picture_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='employee',
            name='talenta_age',
            field=models.CharField(blank=True, help_text='Age dari export Talenta', max_length=32),
        ),
    ]
