# Generated by Django 6.0.6 on 2026-06-19 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_talenta_employee_fields'),
        ('employees', '0012_employee_nik_lookup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.plant'),
        ),
    ]
